- hosts: localhost
  tasks:
    - name: Install Zsh
      package:
        name: zsh
        state: present

    - name: Install Oh My Zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh --unattended)"
      args:
        creates: ~/.oh-my-zsh

    - name: Set Zsh as default shell
      shell: |
        chsh -s $(which zsh)
      args: {}

    - name: Install fontconfig
      apt:
        name: fontconfig
        state: present
      register: fontconfig_installer

    - name: Download Ubuntu Mono font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/UbuntuMono.zip
        dest: /tmp/UbuntuMono.zip

    - name: Ensure font directory exists
      file:
        path: ~/.local/share/fonts
        state: directory

    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present

    - name: Unzip Ubuntu Mono font
      unarchive:
        src: /tmp/UbuntuMono.zip
        dest: ~/.local/share/fonts
        remote_src: yes
        extra_opts: ['-o'] # Use unzip options to overwrite files

    - name: Update font cache
      command: fc-cache -f -v

    - name: Install Starship
      shell: |
        curl -sS https://starship.rs/install.sh | sh -s -- -y
      args:
        creates: ~/.cargo/bin/starship

    - name: Ensure config directory exists
      file:
        path: ~/.config
        state: directory

    - name: Configure Starship
      copy:
        dest: ~/.config/starship.toml
        content: |
          # Starship configuration
          format = """\
          [](bg:#030B16 fg:#7DF9AA)\
          [](bg:#7DF9AA fg:#090c0c)\
          [](fg:#7DF9AA bg:#1C3A5E)\
          $time\
          [](fg:#1C3A5E bg:#3B76F0)\
          $directory\
          [](fg:#3B76F0 bg:#FCF392)\
          $git_branch\
          $git_status\
          $git_metrics\
          [](fg:#FCF392 bg:#030B16)\
          $character\
          """

          [directory]
          format = "[  $path ]($style)"
          style = "fg:#E4E4E4 bg:#3B76F0"

          [git_branch]
          format = '[ $symbol$branch(:$remote_branch) ]($style)'
          symbol = "  "
          style = "fg:#1C3A5E bg:#FCF392"

          [git_status]
          format = '[$all_status]($style)'
          style = "fg:#1C3A5E bg:#FCF392"

          [git_metrics]
          format = "([+$added]($added_style))[]($added_style)"
          added_style = "fg:#1C3A5E bg:#FCF392"
          deleted_style = "fg:bright-red bg:235"
          disabled = false

          [hg_branch]
          format = "[ $symbol$branch ]($style)"
          symbol = " "

          [cmd_duration]
          format = "[  $duration ]($style)"
          style = "fg:bright-white bg:18"

          [character]
          success_symbol = '[ ➜](bold green) '
          error_symbol = '[ ✗](#E84D44) '

          [time]
          disabled = false
          time_format = "%R" # Hour:Minute Format
          style = "bg:#1d2230"
          format = '[[  $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

    - name: Export PATH for Starship
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"

    - name: Initialize Starship prompt for zsh
      lineinfile:
        path: ~/.zshrc
        line: 'eval "$(starship init zsh)"'
        create: yes

    - name: Trigger eval to activate starship
      shell: |
        zsh -c 'source ~/.zshrc && eval "$(starship init zsh)"'
